import type {
  AuditEventResponse,
  HealthResponse,
  IntentDetailResponse,
  ListConnectorsResponse,
  PolicyResponse,
  ReceiptDetailResponse,
} from '@vowgrid/contracts';

export interface DirectoryEntry {
  id: string;
  label: string;
  role?: string;
}

export type ProvisionalIntentRecord = IntentDetailResponse;

export interface ProvisionalWorkspaceData {
  workspaceId: string;
  workspaceName: string;
  notes: string[];
  health: HealthResponse;
  directory: DirectoryEntry[];
  connectors: ListConnectorsResponse;
  policies: PolicyResponse[];
  intents: ProvisionalIntentRecord[];
  auditEvents: AuditEventResponse[];
}

const workspaceId = 'ws_vowgrid_primary';

const directory: DirectoryEntry[] = [
  { id: 'user_ops_lead', label: 'Amina Patel', role: 'Operations lead' },
  { id: 'user_sec_review', label: 'Jonas Reed', role: 'Security reviewer' },
  { id: 'agent_risk_copilot', label: 'Risk Copilot', role: 'Autonomous agent' },
  { id: 'system', label: 'VowGrid system', role: 'System' },
];

const connectors: ListConnectorsResponse = {
  connectors: [
    {
      id: 'conn_mock_primary',
      name: 'Mock Control Connector',
      type: 'mock',
      description: 'Deterministic connector for end-to-end trust workflow demos.',
      rollbackSupport: 'supported',
      workspaceId,
      enabled: true,
      createdAt: '2026-03-15T08:10:00.000Z',
      updatedAt: '2026-03-15T08:10:00.000Z',
    },
    {
      id: 'conn_slack_ops',
      name: 'Slack Operations',
      type: 'slack',
      description: 'Connector skeleton for notifications and approval escalations.',
      rollbackSupport: 'partial',
      workspaceId,
      enabled: true,
      createdAt: '2026-03-15T08:20:00.000Z',
      updatedAt: '2026-03-15T08:20:00.000Z',
    },
  ],
  registeredTypes: [
    { type: 'mock', rollbackSupport: 'supported' },
    { type: 'slack', rollbackSupport: 'partial' },
  ],
};

const policies: PolicyResponse[] = [
  {
    id: 'pol_prod_finance',
    name: 'Production finance threshold',
    description: 'Actions above 25k require explicit human approval.',
    type: 'amount_threshold',
    rules: { amountField: 'amount', requireApprovalAbove: 25000 },
    priority: 100,
    enabled: true,
    workspaceId,
    createdAt: '2026-03-15T07:50:00.000Z',
    updatedAt: '2026-03-15T07:50:00.000Z',
  },
  {
    id: 'pol_delete_guard',
    name: 'Delete action guardrail',
    description: 'Blocks destructive delete actions in production connectors.',
    type: 'action_restriction',
    rules: { blockedActions: ['delete_message'] },
    priority: 90,
    enabled: true,
    workspaceId,
    createdAt: '2026-03-15T07:55:00.000Z',
    updatedAt: '2026-03-15T07:55:00.000Z',
  },
  {
    id: 'pol_connector_scope',
    name: 'Slack actions require visibility',
    description: 'Slack changes must remain inspectable and partially reversible.',
    type: 'connector_restriction',
    rules: { allowedConnectors: ['mock', 'slack'] },
    priority: 80,
    enabled: true,
    workspaceId,
    createdAt: '2026-03-15T08:00:00.000Z',
    updatedAt: '2026-03-15T08:00:00.000Z',
  },
];

const intents: ProvisionalIntentRecord[] = [
  {
    id: 'intent_draft_gap',
    title: 'Provision vendor revocation notice',
    description:
      'Draft intent created from the console and intentionally held at the earliest lifecycle stage.',
    action: 'send_notice',
    connectorId: 'conn_slack_ops',
    agentId: 'agent_risk_copilot',
    workspaceId,
    status: 'draft',
    parameters: { channel: '#vendor-risk', text: 'Pending revocation review' },
    environment: 'production',
    createdAt: '2026-03-15T09:01:00.000Z',
    updatedAt: '2026-03-15T09:05:00.000Z',
    agent: {
      id: 'agent_risk_copilot',
      name: 'Risk Copilot',
      type: 'external',
      workspaceId,
      createdAt: '2026-03-15T07:40:00.000Z',
      updatedAt: '2026-03-15T07:40:00.000Z',
    },
    connector: connectors.connectors[1],
    receipts: [],
    rollbackAttempts: [],
  },
  {
    id: 'intent_prop_001',
    title: 'Send staged approval reminder',
    description: 'Notify stakeholders that an approval gate is about to open.',
    action: 'send_message',
    connectorId: 'conn_slack_ops',
    agentId: 'agent_risk_copilot',
    workspaceId,
    status: 'proposed',
    parameters: { channel: '#approvals', text: 'Approval window opens in 15 minutes.' },
    environment: 'staging',
    createdAt: '2026-03-15T09:20:00.000Z',
    updatedAt: '2026-03-15T09:20:00.000Z',
    agent: {
      id: 'agent_risk_copilot',
      name: 'Risk Copilot',
      type: 'external',
      workspaceId,
      createdAt: '2026-03-15T07:40:00.000Z',
      updatedAt: '2026-03-15T07:40:00.000Z',
    },
    connector: connectors.connectors[1],
    receipts: [],
    rollbackAttempts: [],
  },
  {
    id: 'intent_sim_001',
    title: 'Rotate sandbox API credentials',
    description: 'Prepare sandbox credential rotation for a test connector.',
    action: 'rotate_credentials',
    connectorId: 'conn_mock_primary',
    agentId: 'agent_risk_copilot',
    workspaceId,
    status: 'simulated',
    parameters: { system: 'billing-sandbox', amount: 5000 },
    environment: 'sandbox',
    createdAt: '2026-03-15T08:45:00.000Z',
    updatedAt: '2026-03-15T08:52:00.000Z',
    agent: {
      id: 'agent_risk_copilot',
      name: 'Risk Copilot',
      type: 'external',
      workspaceId,
      createdAt: '2026-03-15T07:40:00.000Z',
      updatedAt: '2026-03-15T07:40:00.000Z',
    },
    connector: connectors.connectors[0],
    simulationResult: {
      id: 'sim_001',
      intentId: 'intent_sim_001',
      summary: 'Credential rotation touches one sandbox secret with full rollback support.',
      estimatedImpact: 'low',
      riskLevel: 'low',
      reversibility: 'full',
      affectedResources: [{ type: 'secret', id: 'billing-sandbox', name: 'Billing Sandbox Secret' }],
      diffPreview: {
        before: { credentialVersion: 'v14', rotationWindow: 'closed' },
        after: { credentialVersion: 'v15', rotationWindow: 'open' },
      },
      warnings: [],
      createdAt: '2026-03-15T08:50:00.000Z',
    },
    policyEvaluations: [
      {
        policyId: 'pol_connector_scope',
        policyName: 'Slack actions require visibility',
        result: 'allow',
        reason: 'Mock connector remains within the allowed catalog.',
      },
      {
        policyId: 'pol_prod_finance',
        policyName: 'Production finance threshold',
        result: 'allow',
        reason: 'Sandbox intent amount is below the approval threshold.',
      },
    ],
    receipts: [],
    rollbackAttempts: [],
  },
  {
    id: 'intent_approval_001',
    title: 'Increase monthly vendor payment cap',
    description: 'Raise the payment approval cap for a strategic supplier.',
    action: 'update_finance_limit',
    connectorId: 'conn_mock_primary',
    agentId: 'agent_risk_copilot',
    workspaceId,
    status: 'pending_approval',
    parameters: { vendor: 'Northwind Robotics', amount: 48000, oldLimit: 25000, newLimit: 48000 },
    environment: 'production',
    createdAt: '2026-03-15T08:15:00.000Z',
    updatedAt: '2026-03-15T08:32:00.000Z',
    agent: {
      id: 'agent_risk_copilot',
      name: 'Risk Copilot',
      type: 'external',
      workspaceId,
      createdAt: '2026-03-15T07:40:00.000Z',
      updatedAt: '2026-03-15T07:40:00.000Z',
    },
    connector: connectors.connectors[0],
    simulationResult: {
      id: 'sim_approval_001',
      intentId: 'intent_approval_001',
      summary: 'Will raise a production finance cap from 25k to 48k for one vendor.',
      estimatedImpact: 'high',
      riskLevel: 'high',
      reversibility: 'partial',
      affectedResources: [{ type: 'vendor_policy', id: 'northwind', name: 'Northwind Robotics' }],
      diffPreview: {
        before: { monthlyCap: 25000, requiresCfoReview: false },
        after: { monthlyCap: 48000, requiresCfoReview: true },
      },
      warnings: ['Raises a live production spend limit.'],
      createdAt: '2026-03-15T08:20:00.000Z',
    },
    approvalRequest: {
      id: 'approval_001',
      intentId: 'intent_approval_001',
      status: 'pending',
      requiredCount: 2,
      currentCount: 1,
      expiresAt: '2026-03-16T08:30:00.000Z',
      createdAt: '2026-03-15T08:25:00.000Z',
      updatedAt: '2026-03-15T08:31:00.000Z',
      decisions: [
        {
          id: 'approval_decision_001',
          approvalRequestId: 'approval_001',
          userId: 'user_ops_lead',
          decision: 'approved',
          rationale: 'Financial ops confirms budget alignment.',
          createdAt: '2026-03-15T08:31:00.000Z',
        },
      ],
    },
    policyEvaluations: [
      {
        policyId: 'pol_prod_finance',
        policyName: 'Production finance threshold',
        result: 'require_approval',
        reason: 'Amount 48000 exceeds approval threshold 25000.',
      },
      {
        policyId: 'pol_connector_scope',
        policyName: 'Slack actions require visibility',
        result: 'allow',
        reason: 'Connector is allowed for tracked changes.',
      },
    ],
    receipts: [],
    rollbackAttempts: [],
  },
  {
    id: 'intent_exec_001',
    title: 'Publish approved connector policy pack',
    description: 'Apply a reviewed policy bundle to the control plane.',
    action: 'publish_policy_pack',
    connectorId: 'conn_mock_primary',
    agentId: 'agent_risk_copilot',
    workspaceId,
    status: 'executing',
    parameters: { packVersion: '2026.03.15', approvals: 3 },
    environment: 'production',
    createdAt: '2026-03-15T07:55:00.000Z',
    updatedAt: '2026-03-15T08:40:00.000Z',
    agent: {
      id: 'agent_risk_copilot',
      name: 'Risk Copilot',
      type: 'external',
      workspaceId,
      createdAt: '2026-03-15T07:40:00.000Z',
      updatedAt: '2026-03-15T07:40:00.000Z',
    },
    connector: connectors.connectors[0],
    simulationResult: {
      id: 'sim_exec_001',
      intentId: 'intent_exec_001',
      summary: 'Policy pack updates 4 guardrails and preserves rollback points.',
      estimatedImpact: 'medium',
      riskLevel: 'medium',
      reversibility: 'full',
      affectedResources: [
        { type: 'policy_pack', id: 'pack_2026_03_15', name: 'Policy Pack 2026.03.15' },
      ],
      diffPreview: {
        before: { version: '2026.03.01', guardrails: 12 },
        after: { version: '2026.03.15', guardrails: 16 },
      },
      warnings: ['Execution touches live workflow controls.'],
      createdAt: '2026-03-15T08:01:00.000Z',
    },
    approvalRequest: {
      id: 'approval_002',
      intentId: 'intent_exec_001',
      status: 'approved',
      requiredCount: 2,
      currentCount: 2,
      expiresAt: '2026-03-16T08:10:00.000Z',
      createdAt: '2026-03-15T08:03:00.000Z',
      updatedAt: '2026-03-15T08:09:00.000Z',
      decisions: [
        {
          id: 'approval_decision_002',
          approvalRequestId: 'approval_002',
          userId: 'user_ops_lead',
          decision: 'approved',
          rationale: 'Ops signed off after reviewing rollout notes.',
          createdAt: '2026-03-15T08:07:00.000Z',
        },
        {
          id: 'approval_decision_003',
          approvalRequestId: 'approval_002',
          userId: 'user_sec_review',
          decision: 'approved',
          rationale: 'Security review completed.',
          createdAt: '2026-03-15T08:09:00.000Z',
        },
      ],
    },
    executionJob: {
      id: 'job_001',
      intentId: 'intent_exec_001',
      status: 'processing',
      attempts: 1,
      maxAttempts: 3,
      idempotencyKey: 'pack-2026-03-15',
      startedAt: '2026-03-15T08:39:00.000Z',
      completedAt: null,
      createdAt: '2026-03-15T08:38:00.000Z',
      updatedAt: '2026-03-15T08:40:00.000Z',
    },
    receipts: [],
    rollbackAttempts: [],
  },
  {
    id: 'intent_receipt_001',
    title: 'Rotate customer support routing token',
    description: 'Production token rotation completed with generated proof.',
    action: 'rotate_token',
    connectorId: 'conn_mock_primary',
    agentId: 'agent_risk_copilot',
    workspaceId,
    status: 'succeeded',
    parameters: { service: 'support-router', environment: 'production' },
    environment: 'production',
    createdAt: '2026-03-15T07:10:00.000Z',
    updatedAt: '2026-03-15T07:26:00.000Z',
    agent: {
      id: 'agent_risk_copilot',
      name: 'Risk Copilot',
      type: 'external',
      workspaceId,
      createdAt: '2026-03-15T07:40:00.000Z',
      updatedAt: '2026-03-15T07:40:00.000Z',
    },
    connector: connectors.connectors[0],
    simulationResult: {
      id: 'sim_receipt_001',
      intentId: 'intent_receipt_001',
      summary: 'Rotates one support routing token with full rollback support.',
      estimatedImpact: 'medium',
      riskLevel: 'medium',
      reversibility: 'full',
      affectedResources: [{ type: 'api_token', id: 'support-router', name: 'Support Router Token' }],
      diffPreview: {
        before: { tokenVersion: 'v7' },
        after: { tokenVersion: 'v8' },
      },
      warnings: ['Dependent services will refresh their credentials.'],
      createdAt: '2026-03-15T07:18:00.000Z',
    },
    approvalRequest: {
      id: 'approval_003',
      intentId: 'intent_receipt_001',
      status: 'approved',
      requiredCount: 1,
      currentCount: 1,
      expiresAt: '2026-03-16T07:17:00.000Z',
      createdAt: '2026-03-15T07:18:00.000Z',
      updatedAt: '2026-03-15T07:19:00.000Z',
      decisions: [
        {
          id: 'approval_decision_004',
          approvalRequestId: 'approval_003',
          userId: 'user_sec_review',
          decision: 'approved',
          rationale: 'Rotation window approved.',
          createdAt: '2026-03-15T07:19:00.000Z',
        },
      ],
    },
    executionJob: {
      id: 'job_002',
      intentId: 'intent_receipt_001',
      status: 'completed',
      attempts: 1,
      maxAttempts: 3,
      idempotencyKey: 'support-rotation-v8',
      result: {
        tokenVersion: 'v8',
        rotatedBy: 'Risk Copilot',
        checksum: 'sha256:9f31aab1',
      },
      startedAt: '2026-03-15T07:20:00.000Z',
      completedAt: '2026-03-15T07:21:14.000Z',
      createdAt: '2026-03-15T07:19:30.000Z',
      updatedAt: '2026-03-15T07:21:14.000Z',
    },
    receipts: [
      {
        id: 'receipt_001',
        intentId: 'intent_receipt_001',
        type: 'execution',
        summary: 'Token rotation completed and proof stored.',
        data: {
          action: 'rotate_token',
          connectorType: 'mock',
          parameters: { service: 'support-router' },
          result: { tokenVersion: 'v8', checksum: 'sha256:9f31aab1' },
          executionJobId: 'job_002',
        },
        duration: 74153,
        createdAt: '2026-03-15T07:21:14.000Z',
      },
    ],
    rollbackAttempts: [],
  },
  {
    id: 'intent_rb_001',
    title: 'Restore connector sandbox webhook',
    description:
      'A rollback attempt failed because the remote endpoint remained locked.',
    action: 'restore_webhook',
    connectorId: 'conn_slack_ops',
    agentId: 'agent_risk_copilot',
    workspaceId,
    status: 'rollback_failed',
    parameters: { channel: '#ops-alerts', webhook: 'alerts-primary' },
    environment: 'production',
    createdAt: '2026-03-15T06:40:00.000Z',
    updatedAt: '2026-03-15T06:58:00.000Z',
    agent: {
      id: 'agent_risk_copilot',
      name: 'Risk Copilot',
      type: 'external',
      workspaceId,
      createdAt: '2026-03-15T07:40:00.000Z',
      updatedAt: '2026-03-15T07:40:00.000Z',
    },
    connector: connectors.connectors[1],
    simulationResult: {
      id: 'sim_rb_001',
      intentId: 'intent_rb_001',
      summary:
        'Webhook restoration touches a production alerting path and only supports partial rollback.',
      estimatedImpact: 'high',
      riskLevel: 'high',
      reversibility: 'partial',
      affectedResources: [{ type: 'webhook', id: 'alerts-primary', name: 'Alerts Primary Webhook' }],
      diffPreview: {
        before: { state: 'disabled' },
        after: { state: 'enabled' },
      },
      warnings: ['Connector rollback capability is partial.'],
      createdAt: '2026-03-15T06:43:00.000Z',
    },
    approvalRequest: {
      id: 'approval_004',
      intentId: 'intent_rb_001',
      status: 'approved',
      requiredCount: 1,
      currentCount: 1,
      expiresAt: '2026-03-16T06:44:00.000Z',
      createdAt: '2026-03-15T06:43:30.000Z',
      updatedAt: '2026-03-15T06:44:30.000Z',
      decisions: [
        {
          id: 'approval_decision_005',
          approvalRequestId: 'approval_004',
          userId: 'user_ops_lead',
          decision: 'approved',
          rationale: 'Approving restoration after incident mitigation.',
          createdAt: '2026-03-15T06:44:30.000Z',
        },
      ],
    },
    executionJob: {
      id: 'job_003',
      intentId: 'intent_rb_001',
      status: 'completed',
      attempts: 1,
      maxAttempts: 3,
      result: { webhook: 'alerts-primary', state: 'enabled' },
      createdAt: '2026-03-15T06:45:00.000Z',
      updatedAt: '2026-03-15T06:46:10.000Z',
      startedAt: '2026-03-15T06:45:08.000Z',
      completedAt: '2026-03-15T06:46:10.000Z',
    },
    receipts: [
      {
        id: 'receipt_002',
        intentId: 'intent_rb_001',
        type: 'execution',
        summary: 'Webhook restored before rollback was requested.',
        data: {
          action: 'restore_webhook',
          connectorType: 'slack',
          result: { webhook: 'alerts-primary', state: 'enabled' },
        },
        duration: 62000,
        createdAt: '2026-03-15T06:46:10.000Z',
      },
    ],
    rollbackAttempts: [
      {
        id: 'rollback_001',
        intentId: 'intent_rb_001',
        status: 'failed',
        reason: 'Remote webhook endpoint was still locked by Slack.',
        result: {
          error:
            'Connector rollback is partial and the endpoint lock prevented reversal.',
        },
        startedAt: '2026-03-15T06:55:00.000Z',
        completedAt: '2026-03-15T06:57:40.000Z',
        createdAt: '2026-03-15T06:55:00.000Z',
      },
    ],
  },
];

const auditEvents: AuditEventResponse[] = [
  {
    id: 'audit_001',
    action: 'intent.created',
    entityType: 'intent',
    entityId: 'intent_draft_gap',
    actorType: 'agent',
    actorId: 'agent_risk_copilot',
    workspaceId,
    metadata: { title: 'Provision vendor revocation notice' },
    createdAt: '2026-03-15T09:01:00.000Z',
  },
  {
    id: 'audit_002',
    action: 'intent.simulated',
    entityType: 'intent',
    entityId: 'intent_approval_001',
    actorType: 'system',
    actorId: 'system',
    workspaceId,
    metadata: { riskLevel: 'high', reversibility: 'partial' },
    createdAt: '2026-03-15T08:20:00.000Z',
  },
  {
    id: 'audit_003',
    action: 'approval.requested',
    entityType: 'intent',
    entityId: 'intent_approval_001',
    actorType: 'system',
    actorId: 'system',
    workspaceId,
    metadata: { approvalRequestId: 'approval_001', requiredCount: 2 },
    createdAt: '2026-03-15T08:25:00.000Z',
  },
  {
    id: 'audit_004',
    action: 'approval.approved',
    entityType: 'intent',
    entityId: 'intent_approval_001',
    actorType: 'user',
    actorId: 'user_ops_lead',
    workspaceId,
    metadata: { approvalRequestId: 'approval_001' },
    createdAt: '2026-03-15T08:31:00.000Z',
  },
  {
    id: 'audit_005',
    action: 'execution.completed',
    entityType: 'intent',
    entityId: 'intent_receipt_001',
    actorType: 'system',
    actorId: 'system',
    workspaceId,
    metadata: { executionJobId: 'job_002', duration: 74153 },
    createdAt: '2026-03-15T07:21:14.000Z',
  },
  {
    id: 'audit_006',
    action: 'rollback.requested',
    entityType: 'intent',
    entityId: 'intent_rb_001',
    actorType: 'user',
    actorId: 'user_sec_review',
    workspaceId,
    metadata: { rollbackAttemptId: 'rollback_001' },
    createdAt: '2026-03-15T06:55:00.000Z',
  },
  {
    id: 'audit_007',
    action: 'execution.failed',
    entityType: 'intent',
    entityId: 'intent_rb_001',
    actorType: 'system',
    actorId: 'system',
    workspaceId,
    metadata: { executionJobId: 'rollback_001', error: 'Endpoint lock prevented reversal.' },
    createdAt: '2026-03-15T06:57:40.000Z',
  },
];

export const provisionalWorkspaceData: ProvisionalWorkspaceData = {
  workspaceId,
  workspaceName: 'Primary Trust Workspace',
  notes: [
    'Provisional adapter is enabled because live API wiring may be absent or unavailable.',
    'Provisional data mirrors the current shared contracts and keeps every lifecycle stage visible for review.',
  ],
  health: {
    status: 'healthy',
    timestamp: '2026-03-15T09:30:00.000Z',
    services: { database: 'healthy', redis: 'healthy' },
    version: '0.1.0',
  },
  directory,
  connectors,
  policies,
  intents,
  auditEvents,
};

export const provisionalReceipts: ReceiptDetailResponse[] = intents.flatMap((intent) =>
  intent.receipts.map((receipt) => ({
    ...receipt,
    intent: {
      id: intent.id,
      workspaceId: intent.workspaceId,
      title: intent.title,
      action: intent.action,
    },
  })),
);
